<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
    $_description = $this->getCurrentCategory()->getDescription();

    //print_r( $_description );
    //print $_description;
    $_cat = $this->getCurrentCategory();
    $data = $_cat->getData();        
    //$attrs = $_cat->getAttributes();
    //print_r($data);

    $_class = "";
    $_helper_shopby = Mage::helper('mocshopbyfix');
    if( $_helper_shopby->isRequestedFilterAttributes() ){
        //$_imgUrl = '';
        $_description = $this->getCurrentCategory()->getDescriptionTemplate();
        $_class = "filtered-attr";
    } else {
        //$_imgUrl = '';
        $_description = '';        
    }
?>

<?php if( $_helper_shopby->_isPageHandled() ): ?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>
<?php endif; ?>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if($_imgUrl): ?>
    <?= $_imgHtml ?>
<?php endif; ?>

<?php /* Custom SEO description for category page with filtered attributes */ ?>
<?php if($_helper_shopby->_isFilteredAttributes()): ?>
    <!-- Custom SEO description -->
    <div class="category-description std <?=$_class?>">
        <?= $this->getSeodescription() ?>
        <?php echo $this->getCmsBlockHtml() ?>
    </div>
<?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php if(empty($_description)): ?>
        <?php echo $this->getCmsBlockHtml() ?>
    <?php endif ?>

<?php elseif($this->isMixedMode()): ?>
    <?php if(empty($_description)): ?>
        <?php echo $this->getCmsBlockHtml() ?>
    <?php endif ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
